version: '3.2'
services:

    integration:
        build: integration/
        depends_on:
            - speech2text
            - text2speech
        
        environment: 
            -TRANSLATION_MAP: "{\"en\": {\"es\": \"http://taln.upf.edu/mmt-en_es/translate\"}}"
        ports: 
            - "4100:80"
            
    speech2text:
        build: speech2text/
        volumes:
            - ./speech2text/ASR:/ASR
        ports:
            - "4200:80"

    text2speech:
        build: text2speech/
        volumes:
            - ./text2speech/models:/models
        ports:
            - "4300:80"
    
    mmt-es_en:
        image: maven-taln.upf.edu/mmt-es_en:var3
        ports:
            - "4400:80"
        deploy:
            replicas: 0
            resources:
                limits:
                    cpus: "1"
                    memory: 2GB


